name: Deploy Next-JS
on:
  push:
    branches: [ SES-62-migrate-project-to-next-js ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Install project
        run: |
          npm install -g yarn
          yarn
          yarn build
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          PASSWORD: ${{ secrets.SSH_PASS }}
          script: |
            pm2 delete next-js
            rm -rf /var/www/next/app
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          PASSWORD: ${{ secrets.SSH_PASS }}
        with:
          source: "./"
          target: "/var/www/next/app"
      - name: Initializing server
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          PASSWORD: ${{ secrets.SSH_PASS }}
          script: |
            cd /var/www/next/app
            pm2 start yarn --name "next-js" -- start
