name: Deploy to Staging
on:
  push:
    branches: [ SES-31-Create-deployments ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v16.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project
        run: |
          npm install
          npm run build --prod
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          PASSWORD: ${{ secrets.SSH_PASS }}
        with:
          source: "./build"
          target: "/var/www/ses-dashboard/uploading/build"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          PASSWORD: ${{ secrets.SSH_PASS }}
          script: |
            cd /var/www/ses-dashboard/
            rm -rf makerdao-ses-dashboard
            cd /var/www/ses-dashboard/uploading/
            mv build/ /var/www/ses-dashboard/makerdao-ses-dashboard/build/
            cd /var/www/ses-dashboard/
            rm -rf uploading/