name: Staging deployment
on:
  push:
    branches: [ SES-73-create-the-environments ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [v16.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Configure environment variables
        run: |
          rm .env
          echo -e NEXT_PUBLIC_GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_API_URL }} >> .env
      - name: Install project
        run: |
          npm install -g yarn
          yarn
          yarn build
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST_PRODUCTION }}
          USERNAME: ${{ secrets.SSH_USER_PRODUCTION }}
          PORT: ${{ secrets.SSH_PORT }}
          PASSWORD: ${{ secrets.SSH_PASS_PRODUCTION }}
        with:
          source: "./"
          target: "/var/www/next/app-production-tmp"
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          PASSWORD: ${{ secrets.SSH_PASS }}
          script: |
            pm2 stop next-js-production
            mv /var/www/next/app-production /var/www/next/app-production-del
            mv /var/www/next/app-production-tmp /var/www/next/app-production
            pm2 start next-js-production
            rm -rf /var/www/next/app-production-del
            rm -rf /var/www/next/app-production-tmp