name: Validating PR
on:
  push:
    branches:
      - SES-48-Configure-eslint
jobs:
  validate-pr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ v16.x ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Install project
        run: |
          npm install -g yarn
          yarn
      - name: Validate
        run: |
          yarn run eslint --fix src/**/*{.ts,.tsx}
          yarn test 
          yarn build --prod
        env:
          CI: true
